### ISSUE TITLE
Support background modes calling screen

### ISSUE THREAD

**Issue by LSmint** [AgoraIO/Flutter-SDK#28]
Will Flutter Agora.io support CallKit (iOS) and ConnectionService (Android) in future?

**Comment by Matrixbirds** [comment]
Did you mean support remote call through Agora.io cloud service?

**Comment by Matrixbirds** [comment]
The native SDK still not support this functional. I m already submit this functional proposal to our teammate. If have any progress i will update here.

**Comment by Anmol92verma** [comment]
Any plans on the integration for the background modes ?

**Comment by LichKing-2234** [comment]
we do not support it in Flutter SDK, maybe you can fork our SDK and add it by yourself.

**Comment by asongkai** [comment]
Hi,

I need this too if your SDK not support did you recommend any other plugin or tools that works with your SDK?

**Comment by LichKing-2234** [comment]
Although we will not integrate Callkit (iOS) and ConnectionService (Android) in the SDK in the near future, if you just want the app to keep calling in the background, you can call `setParameters('{"che.audio.opensl":true}');` on the Android platform(>2.3.2),  enable background mode and select the audio, airplay, picture in picture, and voice over IP options on the IOS platform.

![image](https://user-images.githubusercontent.com/9312526/97386080-0770c680-190e-11eb-90f0-9fa16150a765.png)

**Comment by fareesh** [comment]
Does anyone have a working project with some example code to confirm if this approach is working for Android ?

**Comment by rafekun** [comment]
@LichKing-2234 Where should I put `setParameters('{"che.audio.opensl":true}');`?

**Comment by zubke** [comment]
For Android there is still an issue in the background. Microphone input is gone when a few minutes in the background. The suggested solution doesn't make a change. So there certainly is a bug. Running the service in a Foreground service would be a solution, but that isn't easy in flutter without changing the plugin itself. I think the solution should come from the agora plugin itself. Are there plans to solve this issue?

**Comment by LichKing-2234** [comment]
@zubke you can use one of them from [pub.dev](`https://pub.dev/flutter/packages?q=foreground+service`), you just need to start a foreground service.

**Comment by abdullah432** [comment]
> @LichKing-2234 Where should I put `setParameters('{"che.audio.opensl":true}');`?
> iOS works fine, thanks!!

How it is working. Can you explain. Did you use a plugin or so just "select the Audio, Airplay, and Picture in Picture, and Voice over IP options on the IOS platform." works?

**Comment by LichKing-2234** [comment]
@abdullah432 should use foreground service on Android, just select the `Audio, Airplay, and Picture in Picture, and Voice over IP` options on the IOS platform

**Comment by JayPerfetto** [comment]
Can you please explain the fix for android beyond "use foreground service"? I understand that is a plugin unrelated to Agora, but if you know how to do it and the rest of us do not, your developers rely on you to communicate clearly how to make this plugin work on all platforms as expected.

**Comment by braysonjohn148** [comment]
`await FlutterForegroundPlugin.startForegroundService(
        holdWakeLock: true,
        onStarted: () {
          //initialize(); 
        }, 
        title: "",
        content: "",
        iconName: "");`
        
        This is how i implemented foreground_services. When my app is sent to background. It is not killed. I want to know where do i initialize the agora. Where i commented out?? Because i get an error. Initialize this while the other one is not killed.

**Comment by vedartm** [comment]
@LichKing-2234. I am still not with android part. Can you share any code snippet that helps with foreground services. I am not sure if @braysonjohn148 was able to achieve it with his snippet.

**Comment by LichKing-2234** [comment]
@vedartm you can use the flutter plugin about `ForegroundService`.

**Comment by elaishane** [comment]
Hey, guys do anybody has the proper solution with a repo for running agora or any other voice SDK in the background for android and ios. I checked the whole issue. but couldn't find a proper solution. I need it urgently for my app. Thank you.

**Comment by LichKing-2234** [comment]
> Although we will not integrate Callkit (iOS) and ConnectionService (Android) in the SDK in the near future, if you just want the app to keep calling in the background, you can call `setParameters('{"che.audio.opensl":true}');` on the Android platform(>2.3.2), enable `Background Modes` and select the `Audio, Airplay, and Picture in Picture`, and `Voice over IP` options on the IOS platform.
> 
> ![image](https://user-images.githubusercontent.com/9312526/97386080-0770c680-190e-11eb-90f0-9fa16150a765.png)

@elaishane for iOS use

**Comment by Rohithgilla12** [comment]
FYI the foreground service package is not nu safe.

**Comment by CodingAleCR** [comment]
I have not tried it, but I found this other plugin for foreground services in Android that is null safety compatible: https://pub.dev/packages/flutter_background

**Comment by isiyemijoe** [comment]
I'm not sure @LichKing-2234  knows how to implement the foreground service for android he's suggesting, because all everyone need is a simple code snippet, where should we put setParameters('{"che.audio.opensl":true}'); in our code. Pls help if you do.

**Comment by isiyemijoe** [comment]
RtcEngine  _engine = await RtcEngine.create(
      appId,
    );
    _engine.setParameters('{"che.audio.opensl":true}');

**Comment by LichKing-2234** [comment]
> RtcEngine _engine = await RtcEngine.create( appId, ); _engine.setParameters('{"che.audio.opensl":true}');

this is not helpful, pls use https://pub.dev/packages/foreground_service

**Comment by FatimaZahra-FCH** [comment]
I tried using foreground_service but I'm having black screen issue both on the local and remote sides

**Comment by LichKing-2234** [comment]
@FatimaZahra-FCH Could you pls explain your issue?

**Comment by FatimaZahra-FCH** [comment]
@LichKing-2234 During a call between 2 devices X and Y, when I turn off the screen of device X and after 1 minute I noticed that the camera view on device Y freezes. (I need to display camera feedback even if the remote device goes into sleep mode.)
Then to solve this problem I tried using the foreground_service you recommended but now the camera view never shows whether its in sleep mode or not (black screen on both devices X and Y)

**Comment by LichKing-2234** [comment]
if you enable foreground_service, the audio or video capture will keep on background mode.

**Comment by FatimaZahra-FCH** [comment]
@LichKing-2234 What do you mean by "enabling" foreground_service ?
I'm using this plugin : [https://pub.dev/packages/foreground_service], I moved all the agora related code to the foreground service and I'm using sendToPort() to communicate data between my app and the foreground service and everything is working fine except the black screen issue. I don't have any problem with the audio / RTM / both users are successfully joining the channel .... the only problem is the black camera capture !

Can you please give me an example of how you made it work ?

**Comment by jayant1441** [comment]
Did anyone found the solution

**Comment by FatimaZahra-FCH** [comment]
@LichKing-2234 , Still waiting for an answer ...

**Comment by Codesait** [comment]
> if you enable foreground_service, the audio or video capture will keep on background mode.

It will not be painful to you sir to help out by providing a code snippet solving this issue on background sir
